# Generated by Django 5.1.5 on 2025-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajainventario',
            name='tipo_baja',
            field=models.CharField(choices=[('inicio', 'Inicio de Turno'), ('medio', 'Medio Turno'), ('final', 'Final de Turno'), ('no_utilizado', 'No Utilizado')], default='inicio', max_length=15),
        ),
    ]
