# Generated by Django 5.1.5 on 2025-05-03 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_bajainventario_tipo_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='notas_proveedor/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='tasks.proveedor')),
            ],
        ),
    ]
