# Generated by Django 5.1.6 on 2025-04-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categoria_platillococina_proveedor_inventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='actualizado_en',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
    ]
