# Generated by Django 5.1.6 on 2025-04-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_inventario_actualizado_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='nombre_proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
    ]
