# Generated by Django 5.1.6 on 2025-04-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_nombre_proveedor_nombre_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='limite_stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventario',
            name='para_barra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='para_cocina',
            field=models.BooleanField(default=False),
        ),
    ]
