# Generated by Django 5.1.6 on 2025-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_inventario_limite_stock_inventario_para_barra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventabarra',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ventabarra',
            name='area',
            field=models.CharField(choices=[('barra', 'Barra'), ('cocina', 'Cocina')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventabarra',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(),
        ),
    ]
