# Generated by Django 5.1.6 on 2025-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_ventabarra_usuario_ventabarra_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventabarra',
            name='area',
            field=models.CharField(choices=[('barra', 'Barra'), ('cocina', 'Cocina')], default='barra', max_length=50),
        ),
    ]
