# Generated by Django 5.1.6 on 2025-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_ventabarra_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='unidad',
            field=models.CharField(choices=[('pz', 'Pieza'), ('g', 'Gramo'), ('kg', 'Kilogramo'), ('ml', 'Mililitro'), ('l', 'Litro')], max_length=20),
        ),
    ]
