# Generated by Django 5.1.6 on 2025-04-29 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_bajainventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='limite_stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre_producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.proveedor'),
        ),
    ]
